name: nanolyse
description: DNA contaminant removal using NanoLyse
keywords:
    - contaminant_removal
tools:
    - nanolyse:
        description: |
            DNA contaminant removal using NanoLyse
        homepage: https://github.com/wdecoster/nanolyse
        documentation: https://github.com/wdecoster/nanolyse#nanolyse
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: |
            Basecalled reads in FASTQ.GZ format
    - nanolyse_fasta:
        type: file
        description: |
            A reference fasta file against which to filter.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: Reads with contaminants removed in FASTQ format
        pattern: "*.clean.fastq.gz"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@yuukiiwa"
