name: graphmap2_align
description: A versatile pairwise aligner for genomic and spliced nucleotide sequences
keywords:
    - align
    - fasta
    - fastq
    - genome
    - reference
tools:
    - graphmap2:
        description: |
            A versatile pairwise aligner for genomic and spliced nucleotide sequences.
        homepage: https://github.com/lh3/minimap2
        documentation: https://github.com/lh3/minimap2#uguide
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: |
            List of input FASTQ files
            and paired-end data, respectively.
    - fasta:
        type: file
        description: |
            Reference database in FASTA format.
    - index:
        type: file
        description: |
            FASTA index in gmidx.
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - sam:
        type: file
        description: Alignment in SAM format
        pattern: "*.sam"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@yuukiiwa"
