name: qcat
description: Demultiplexer for Nanopore samples
keywords:
    - demultiplex

tools:
    - qcat:
        description: |
            A demultiplexer for Nanopore samples
        homepage: https://github.com/nanoporetech/qcat
        documentation: https://github.com/nanoporetech/qcat#qcat
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - input_path:
        type: file
        description: |
            Non-demultiplexed Nanopore sequencing sample.

output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: Demultiplexed fastq samples
        pattern: "*.fastq.gz"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@yuukiiwa"
