name: bedtools_bamtobed
description: Converts a bam file to a bed12 file.
keywords:
    - bam
    - bed
tools:
    - bedtools:
        description: |
            A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
        documentation: https://bedtools.readthedocs.io/en/latest/content/tools/complement.html
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Input BAM file
        pattern: "*.{bam}"
    - sizes:
        type: file
        description: File which defines the chromosome lengths for a given genome
        pattern: "*.{sizes}"
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - bed12:
        type: file
        description: Bed file with 12 columns containing all genomic intervals.
        pattern: "*.{bed}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@yuukiiwa"
